client_id = "70b22ff11e774dcf49ef9b50c6147654"
name = "merchy"
application_url = "https://merchy-frontend-nwbb.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "https://merchyapp-backend.up.railway.app/webhooks/app_subscriptions_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://merchyapp-backend.up.railway.app/webhooks"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://merchyapp-backend.up.railway.app/webhooks"

[access_scopes]
scopes = "read_orders,read_products"

[auth]
redirect_urls = ["https://merchyapp-backend.up.railway.app/auth/callback"]
