"""add billing columns to shops

Revision ID: 27f87d4b4bff
Revises: 8d3e8dba1f2d
Create Date: 2026-04-09 12:59:09.121361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f87d4b4bff'
down_revision: Union[str, Sequence[str], None] = '8d3e8dba1f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'trial_ends_at')
    op.drop_column('shops', 'subscription_status')
    op.drop_column('shops', 'subscription_id')
    # ### end Alembic commands ###
