"""add variant location based inventory and sales

Revision ID: 9fdedd4141f6
Revises: 27f87d4b4bff
Create Date: 2026-05-03 20:20:25.475553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdedd4141f6'
down_revision: Union[str, Sequence[str], None] = '27f87d4b4bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_location_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventory', sa.Column('variant_id', sa.BigInteger(), nullable=False))
    op.add_column('inventory', sa.Column('location_id', sa.BigInteger(), nullable=False))
    op.add_column('inventory', sa.Column('variant_title', sa.String(length=100), nullable=True))
    op.add_column('inventory', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('inventory', 'sku',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index('idx_inventory_shop_variant', 'inventory', ['shop_id', 'variant_id'], unique=False)
    op.create_unique_constraint('uq_inventory_variant_location', 'inventory', ['shop_id', 'variant_id', 'location_id'])
    op.drop_column('inventory', 'color')
    op.drop_column('inventory', 'size')
    op.add_column('sales', sa.Column('variant_id', sa.BigInteger(), nullable=False))
    op.add_column('sales', sa.Column('variant_title', sa.String(length=100), nullable=True))
    op.alter_column('sales', 'sku',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('sales', 'quantity_sold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_sales_shop_variant_date', 'sales', ['shop_id', 'variant_id', 'created_at'], unique=False)
    op.drop_column('sales', 'color')
    op.drop_column('sales', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('size', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('idx_sales_shop_variant_date', table_name='sales')
    op.alter_column('sales', 'quantity_sold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'sku',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('sales', 'variant_title')
    op.drop_column('sales', 'variant_id')
    op.add_column('inventory', sa.Column('size', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_inventory_variant_location', 'inventory', type_='unique')
    op.drop_index('idx_inventory_shop_variant', table_name='inventory')
    op.alter_column('inventory', 'sku',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('inventory', 'updated_at')
    op.drop_column('inventory', 'variant_title')
    op.drop_column('inventory', 'location_id')
    op.drop_column('inventory', 'variant_id')
    op.drop_table('shop_location_preferences')
    op.drop_table('locations')
    # ### end Alembic commands ###
